//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denikarabencBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("denikarabencBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !addcommand.
        /// </summary>
        internal static string botCommandPool_ADDCOMMAND {
            get {
                return ResourceManager.GetString("botCommandPool_ADDCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added.
        /// </summary>
        internal static string botCommandPool_ADDED {
            get {
                return ResourceManager.GetString("botCommandPool_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist.
        /// </summary>
        internal static string botCommandPool_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("botCommandPool_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string botCommandPool_COMMAND {
            get {
                return ResourceManager.GetString("botCommandPool_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        internal static string botCommandPool_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("botCommandPool_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !editcommand.
        /// </summary>
        internal static string botCommandPool_EDITCOMMAND {
            get {
                return ResourceManager.GetString("botCommandPool_EDITCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edited to.
        /// </summary>
        internal static string botCommandPool_EDITED_TO {
            get {
                return ResourceManager.GetString("botCommandPool_EDITED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !follow.
        /// </summary>
        internal static string botCommandPool_FOLLOW {
            get {
                return ResourceManager.GetString("botCommandPool_FOLLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instead.
        /// </summary>
        internal static string botCommandPool_INSTEAD {
            get {
                return ResourceManager.GetString("botCommandPool_INSTEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PING :tmi.twitch.tv.
        /// </summary>
        internal static string botCommandPool_PINGCOMMAND {
            get {
                return ResourceManager.GetString("botCommandPool_PINGCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !title.
        /// </summary>
        internal static string botCommandPool_TITLE {
            get {
                return ResourceManager.GetString("botCommandPool_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string botCommandPool_USE {
            get {
                return ResourceManager.GetString("botCommandPool_USE", resourceCulture);
            }
        }
    }
}
