//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denikarabencBotOBSSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("denikarabencBotOBSSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating basic backup.
        /// </summary>
        internal static string OBSConfiguration_CREATING_BASIC_BACKUP {
            get {
                return ResourceManager.GetString("OBSConfiguration_CREATING_BASIC_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating scenes backup.
        /// </summary>
        internal static string OBSConfiguration_CREATING_SCENES_BACKUP {
            get {
                return ResourceManager.GetString("OBSConfiguration_CREATING_SCENES_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denikarabencBot Clip.
        /// </summary>
        internal static string OBSConfiguration_DENIKARABENCBOT_CLIP {
            get {
                return ResourceManager.GetString("OBSConfiguration_DENIKARABENCBOT_CLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denikarabencBot Replay.
        /// </summary>
        internal static string OBSConfiguration_DENIKARABENCBOT_REPLAY {
            get {
                return ResourceManager.GetString("OBSConfiguration_DENIKARABENCBOT_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string OBSConfiguration_DONE {
            get {
                return ResourceManager.GetString("OBSConfiguration_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser_source.
        /// </summary>
        internal static string OBSConfiguration_OBS_SCENE_ID_BROWSER_SOURCE {
            get {
                return ResourceManager.GetString("OBSConfiguration_OBS_SCENE_ID_BROWSER_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoWindow:HwndWrapper[denikarabencBot.exe;;0b9eb312-851e-4863-b66a-6136abfe8b15]:denikarabencBot.exe.
        /// </summary>
        internal static string OBSConfiguration_OBS_SCENE_ID_REPLAY_SETTING_WINDOW {
            get {
                return ResourceManager.GetString("OBSConfiguration_OBS_SCENE_ID_REPLAY_SETTING_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window_capture.
        /// </summary>
        internal static string OBSConfiguration_OBS_SCENE_ID_WINDOW_CAPTURE {
            get {
                return ResourceManager.GetString("OBSConfiguration_OBS_SCENE_ID_WINDOW_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up basic configuration.
        /// </summary>
        internal static string OBSConfiguration_SETTING_UP_BASIC_CONFIGURATION {
            get {
                return ResourceManager.GetString("OBSConfiguration_SETTING_UP_BASIC_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up scenes configuration.
        /// </summary>
        internal static string OBSConfiguration_SETTING_UP_SCENES_CONFIGURATION {
            get {
                return ResourceManager.GetString("OBSConfiguration_SETTING_UP_SCENES_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting configuration.
        /// </summary>
        internal static string OBSConfiguration_STARTING_CONFIGURATION {
            get {
                return ResourceManager.GetString("OBSConfiguration_STARTING_CONFIGURATION", resourceCulture);
            }
        }
    }
}
